### ISSUE TITLE
why json is enforced applied?

### ISSUE THREAD

**Issue by nikoloss** [socketry/roda-websockets#1]
Dude, excellent job there!  But I think it would narrow its usage if json is an enforced choice. I prefer raw message like Protocol::WebSocket::Connection provided. What u say?

**Comment by ioquatix** [comment]
It's fine, but can you make a PR so we can see what you want?

**Comment by ioquatix** [comment]
If you change

https://github.com/socketry/roda-websockets/blob/2a736f8883611a9eef698fd9b238b4fa39fc61bc/lib/roda/plugins/websockets.rb#L52

to 

`*arguments, **options` and pass it through you can specify your own connection class.

**Comment by nikoloss** [comment]
I've read your source code and this issue should be placed in [async-websocket](https://github.com/socketry/async-websocket).
